"""Parse a raw pdflatex/xelatex/latexmk log into structured errors/warnings
(Plan.md §7.9, Phase 4). Built against real logs generated by our own
sandbox (apps/compile) for: an undefined-control-sequence error, a
runaway-argument error with no line number, an undefined-reference warning,
an Overfull \\hbox warning, and a halt-on-error single-error case — see
projects/test_log_parser.py for those fixtures.

File tracking is a best-effort approximation, not a real TeX-engine-grade
parser: TeX logs mark which file is "current" with a paren-matching
convention (`(./main.tex ... (/path/to/other.sty ...) ...)`), which this
mimics via a simple stack fed by scanning the whole log for `(<path>` opens
and bare `)` closes in order. Pathological cases (wrapped filenames,
malformed nesting) can throw the stack off — good enough for "which file
was open when this error happened" in the common case, not a guarantee.
"""

import re
from dataclasses import dataclass, field

_ERROR_RE = re.compile(r"^! (.+)")
_ERROR_TRAILER_RE = re.compile(r"^!\s+==>")  # "!  ==> Fatal error occurred..." — not a new error
_LINE_NUM_RE = re.compile(r"^l\.(\d+)\b")
_WARNING_RE = re.compile(r"(?:^|:\s*)(?:LaTeX|Package \S+|Class \S+|pdfTeX) Warning:\s*(.+)")
_ON_INPUT_LINE_RE = re.compile(r"on input line (\d+)")
_BOX_WARNING_RE = re.compile(r"^(Overfull|Underfull) \\([hv])box .*?(?:at lines? (\d+)(?:--(\d+))?)?\s*$")
_FILE_TOKEN_RE = re.compile(r"\((?P<open>\.{1,2}/[^\s()]+|/[^\s()]+)|(?P<close>\))")

# latexmk reruns the engine (pdflatex/xelatex) several times per compile to
# resolve citations/references/labels, and our captured "log" is its stdout
# for *all* of those reruns concatenated (see apps/compile/sandbox.py — it's
# `docker logs`, not the single-run .log file). Scanning the whole thing
# would surface e.g. "Citation undefined" warnings from an early pass even
# once a later pass resolves them. Each engine invocation announces itself
# with a "This is pdfTeX/XeTeX/LuaTeX, Version ..." banner, so only the
# segment after the *last* one reflects the compile's final, authoritative
# state.
_RUN_START_RE = re.compile(r"^This is \S*TeX,", re.MULTILINE)


def _last_engine_run(log: str) -> str:
    starts = [m.start() for m in _RUN_START_RE.finditer(log)]
    return log[starts[-1]:] if starts else log

# Only these look like source-ish files worth surfacing as "file" in a
# diagnostic — system package/class files clutter the UI more than help it,
# but we still need to push/pop them on the stack to track nesting correctly.
_SOURCE_EXT_RE = re.compile(r"\.(tex|bib)$")


@dataclass
class Diagnostic:
    message: str
    file: str | None = None
    line: int | None = None


@dataclass
class ParsedLog:
    errors: list[Diagnostic] = field(default_factory=list)
    warnings: list[Diagnostic] = field(default_factory=list)


def _normalize_file(path: str) -> str:
    return path[2:] if path.startswith("./") else path


def parse_log(log: str) -> ParsedLog:
    lines = _last_engine_run(log).splitlines()
    result = ParsedLog()
    file_stack: list[str] = []

    def current_source_file() -> str | None:
        for f in reversed(file_stack):
            if _SOURCE_EXT_RE.search(f):
                return _normalize_file(f)
        return None

    def find_line_number(start: int) -> int | None:
        for j in range(start, min(start + 15, len(lines))):
            if _ERROR_RE.match(lines[j]):
                break  # next error — stop, don't misattribute its context
            m = _LINE_NUM_RE.match(lines[j])
            if m:
                return int(m.group(1))
        return None

    for i, line in enumerate(lines):
        box_match = _BOX_WARNING_RE.match(line)
        # Box-warning lines carry a "(795.00232pt too wide)" aside whose
        # closing paren isn't a file-tracking close — scanning it would pop
        # the actually-open source file off the stack one line too early.
        if not box_match:
            for m in _FILE_TOKEN_RE.finditer(line):
                if m.group("open"):
                    file_stack.append(m.group("open"))
                elif file_stack:
                    file_stack.pop()

        error_match = _ERROR_RE.match(line)
        if error_match and not _ERROR_TRAILER_RE.match(line):
            result.errors.append(
                Diagnostic(
                    message=error_match.group(1).strip(),
                    file=current_source_file(),
                    line=find_line_number(i + 1),
                )
            )
            continue

        warning_match = _WARNING_RE.search(line)
        if warning_match:
            input_line_match = _ON_INPUT_LINE_RE.search(line)
            result.warnings.append(
                Diagnostic(
                    message=warning_match.group(1).strip(),
                    file=current_source_file(),
                    line=int(input_line_match.group(1)) if input_line_match else None,
                )
            )
            continue

        if box_match:
            kind, axis, line_start, _line_end = box_match.groups()
            result.warnings.append(
                Diagnostic(
                    message=f"{kind} \\{axis}box",
                    file=current_source_file(),
                    line=int(line_start) if line_start else None,
                )
            )

    return result
