"""Tests for log_parser.py, built against real logs generated by our own
compile sandbox (apps/compile) for an undefined-control-sequence error, a
runaway-argument/missing-brace error with no line number, an
undefined-reference warning, an Overfull \\hbox warning, and a
halt-on-error single-error case."""

from django.test import SimpleTestCase

from .log_parser import parse_log

UNDEFINED_CONTROL_SEQUENCE_LOG = """\
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdflatex)
entering extended mode
(./main.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-01-16>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
(/work/out/main.aux)
! Undefined control sequence.
l.3 \\thiscommanddoesnotexist

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on /work/out/main.log.
"""

MISSING_BRACE_LOG = """\
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdflatex)
entering extended mode
(./main.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-01-16>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
(/work/out/main.aux))
Runaway argument?
{unterminated \\end {document}
! File ended while scanning use of \\textbf .
<inserted text>
                \\par
<*> main.tex

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on /work/out/main.log.
"""

UNDEFINED_REF_LOG = """\
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdflatex)
entering extended mode
(./main.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-01-16>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
(/work/out/main.aux)

LaTeX Warning: Reference `fig:doesnotexist' on page 1 undefined on input line 3
.

[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (/work/out/main.aux)

LaTeX Warning: There were undefined references.

Output written on /work/out/main.pdf (1 page, 23564 bytes).
"""

OVERFULL_HBOX_LOG = """\
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdflatex)
entering extended mode
(./main.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-01-16>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
(/work/out/main.aux)
Overfull \\hbox (795.00232pt too wide) in paragraph at lines 3--4
\\OT1/cmr/m/n/10 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (/work/out/main.aux) )
Output written on /work/out/main.pdf (1 page, 9288 bytes).
"""


class ParseLogTests(SimpleTestCase):
    def test_undefined_control_sequence_has_file_and_line(self):
        parsed = parse_log(UNDEFINED_CONTROL_SEQUENCE_LOG)
        self.assertEqual(len(parsed.errors), 1)
        self.assertEqual(parsed.errors[0].message, "Undefined control sequence.")
        self.assertEqual(parsed.errors[0].file, "main.tex")
        self.assertEqual(parsed.errors[0].line, 3)
        self.assertEqual(parsed.warnings, [])

    def test_missing_brace_error_with_no_line_number(self):
        parsed = parse_log(MISSING_BRACE_LOG)
        self.assertEqual(len(parsed.errors), 1)
        self.assertEqual(parsed.errors[0].message, "File ended while scanning use of \\textbf .")
        self.assertIsNone(parsed.errors[0].line)

    def test_undefined_reference_warning_has_file_and_line(self):
        parsed = parse_log(UNDEFINED_REF_LOG)
        self.assertEqual(len(parsed.warnings), 2)
        self.assertIn("fig:doesnotexist", parsed.warnings[0].message)
        self.assertEqual(parsed.warnings[0].file, "main.tex")
        self.assertEqual(parsed.warnings[0].line, 3)
        self.assertEqual(parsed.errors, [])

    def test_overfull_hbox_warning_attributes_current_file(self):
        parsed = parse_log(OVERFULL_HBOX_LOG)
        self.assertEqual(len(parsed.warnings), 1)
        self.assertEqual(parsed.warnings[0].message, "Overfull \\hbox")
        self.assertEqual(parsed.warnings[0].file, "main.tex")
        self.assertEqual(parsed.warnings[0].line, 3)

    def test_empty_log_has_no_diagnostics(self):
        parsed = parse_log("")
        self.assertEqual(parsed.errors, [])
        self.assertEqual(parsed.warnings, [])

    def test_multiple_error_markers_are_parsed_as_separate_errors(self):
        parsed = parse_log(UNDEFINED_CONTROL_SEQUENCE_LOG + "\n! A second error.\n")
        self.assertEqual(len(parsed.errors), 2)
        self.assertEqual(parsed.errors[1].message, "A second error.")
