"""Tests for log_parser.py, built against real logs generated by our own
compile sandbox (apps/compile) for an undefined-control-sequence error, a
runaway-argument/missing-brace error with no line number, an
undefined-reference warning, an Overfull \\hbox warning, a halt-on-error
single-error case, and (for the fix-it assistant) two real undefined-command
logs where the command name only appears on a following context line."""

from django.test import SimpleTestCase

from .log_parser import parse_log

UNDEFINED_CONTROL_SEQUENCE_LOG = """\
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdflatex)
entering extended mode
(./main.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-01-16>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
(/work/out/main.aux)
! Undefined control sequence.
l.3 \\thiscommanddoesnotexist

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on /work/out/main.log.
"""

MISSING_BRACE_LOG = """\
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdflatex)
entering extended mode
(./main.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-01-16>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
(/work/out/main.aux))
Runaway argument?
{unterminated \\end {document}
! File ended while scanning use of \\textbf .
<inserted text>
                \\par
<*> main.tex

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on /work/out/main.log.
"""

UNDEFINED_REF_LOG = """\
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdflatex)
entering extended mode
(./main.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-01-16>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
(/work/out/main.aux)

LaTeX Warning: Reference `fig:doesnotexist' on page 1 undefined on input line 3
.

[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (/work/out/main.aux)

LaTeX Warning: There were undefined references.

Output written on /work/out/main.pdf (1 page, 23564 bytes).
"""

MULTI_RUN_RESOLVED_CITATION_LOG = """\
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdflatex)
entering extended mode
(./main.tex
(/work/out/main.aux)
LaTeX Warning: Citation `shannon1948' on page 1 undefined on input line 5.
LaTeX Warning: There were undefined references.
Output written on /work/out/main.pdf (1 page, 20000 bytes).
This is BibTeX, Version 0.99d
The top-level auxiliary file: main.aux
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdflatex)
entering extended mode
(./main.tex
(/work/out/main.aux)
Output written on /work/out/main.pdf (1 page, 23564 bytes).
"""

UNDEF_TOPRULE_LOG = """\
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdflatex)
entering extended mode
(./main.tex
LaTeX2e <2022-11-01> patch level 1
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(./main.aux)

! Undefined control sequence.
l.4 \\toprule

The control sequence at the end of the top line
of your error message was never \\def'ed.

! Undefined control sequence.
<recently read> \\bottomrule

l.6 \\bottomrule

The control sequence at the end of the top line
of your error message was never \\def'ed.

Output written on main.pdf (1 page, 10814 bytes).
"""

UNDEF_MULTIROW_LOG = """\
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdflatex)
entering extended mode
(./main.tex
LaTeX2e <2022-11-01> patch level 1
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(./main.aux)

! Undefined control sequence.
l.4 \\multirow
             {2}{*}{x} & b \\\\
The control sequence at the end of the top line
of your error message was never \\def'ed.

Output written on main.pdf (1 page, 11628 bytes).
"""

TRAILING_BIBTEX_RUN_LOG = """\
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdflatex)
entering extended mode
(./main.tex
(/work/out/main.aux)

! Undefined control sequence.
l.16 \\multirow
              {2}{*}{1 3 3} & 4 & 5 \\\\

LaTeX Warning: Citation `shannon1948' on page 1 undefined on input line 5.
Output written on /work/out/main.pdf (1 page, 20000 bytes).
This is BibTeX, Version 0.99d
The top-level auxiliary file: main.aux
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdflatex)
entering extended mode
(./main.tex
(/work/out/main.aux)

! Undefined control sequence.
l.16 \\multirow
              {2}{*}{1 3 3} & 4 & 5 \\\\

LaTeX Warning: There were undefined references.
Output written on /work/out/main.pdf (1 page, 23564 bytes).
This is BibTeX, Version 0.99d
The top-level auxiliary file: main.aux
"""

OVERFULL_HBOX_LOG = """\
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian) (preloaded format=pdflatex)
entering extended mode
(./main.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-01-16>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def)
(/work/out/main.aux)
Overfull \\hbox (795.00232pt too wide) in paragraph at lines 3--4
\\OT1/cmr/m/n/10 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (/work/out/main.aux) )
Output written on /work/out/main.pdf (1 page, 9288 bytes).
"""


class ParseLogTests(SimpleTestCase):
    def test_undefined_control_sequence_has_file_and_line(self):
        parsed = parse_log(UNDEFINED_CONTROL_SEQUENCE_LOG)
        self.assertEqual(len(parsed.errors), 1)
        self.assertEqual(parsed.errors[0].message, "Undefined control sequence: \\thiscommanddoesnotexist")
        self.assertEqual(parsed.errors[0].file, "main.tex")
        self.assertEqual(parsed.errors[0].line, 3)
        self.assertEqual(parsed.warnings, [])

    def test_missing_brace_error_with_no_line_number(self):
        parsed = parse_log(MISSING_BRACE_LOG)
        self.assertEqual(len(parsed.errors), 1)
        self.assertEqual(parsed.errors[0].message, "File ended while scanning use of \\textbf .")
        self.assertIsNone(parsed.errors[0].line)

    def test_undefined_reference_warning_has_file_and_line(self):
        parsed = parse_log(UNDEFINED_REF_LOG)
        self.assertEqual(len(parsed.warnings), 2)
        self.assertIn("fig:doesnotexist", parsed.warnings[0].message)
        self.assertEqual(parsed.warnings[0].file, "main.tex")
        self.assertEqual(parsed.warnings[0].line, 3)
        self.assertEqual(parsed.errors, [])

    def test_overfull_hbox_warning_attributes_current_file(self):
        parsed = parse_log(OVERFULL_HBOX_LOG)
        self.assertEqual(len(parsed.warnings), 1)
        self.assertEqual(parsed.warnings[0].message, "Overfull \\hbox")
        self.assertEqual(parsed.warnings[0].file, "main.tex")
        self.assertEqual(parsed.warnings[0].line, 3)

    def test_empty_log_has_no_diagnostics(self):
        parsed = parse_log("")
        self.assertEqual(parsed.errors, [])
        self.assertEqual(parsed.warnings, [])

    def test_multiple_error_markers_are_parsed_as_separate_errors(self):
        parsed = parse_log(UNDEFINED_CONTROL_SEQUENCE_LOG + "\n! A second error.\n")
        self.assertEqual(len(parsed.errors), 2)
        self.assertEqual(parsed.errors[1].message, "A second error.")

    def test_undefined_control_sequence_captures_command_direct_and_recently_read(self):
        # Real sandbox output for \toprule/\bottomrule without booktabs: the
        # first error's command is on the very next `l.N` line, the second's
        # is announced by an intervening `<recently read>` line first — both
        # shapes must resolve to the same enriched message format.
        parsed = parse_log(UNDEF_TOPRULE_LOG)
        self.assertEqual(len(parsed.errors), 2)
        self.assertEqual(parsed.errors[0].message, "Undefined control sequence: \\toprule")
        self.assertEqual(parsed.errors[1].message, "Undefined control sequence: \\bottomrule")

    def test_undefined_control_sequence_command_stops_at_argument_brace(self):
        # \multirow{2}{*}{x} — the command name shouldn't swallow its braces.
        parsed = parse_log(UNDEF_MULTIROW_LOG)
        self.assertEqual(len(parsed.errors), 1)
        self.assertEqual(parsed.errors[0].message, "Undefined control sequence: \\multirow")

    def test_trailing_bibtex_run_does_not_shadow_the_real_final_pdflatex_run(self):
        # Real bug: for a \bibliography (bibtex, not biblatex) document,
        # latexmk's actual rule order can legitimately end on a bibtex
        # invocation (pdflatex -> bibtex -> pdflatex -> bibtex again) — its
        # "This is BibTeX, Version ..." banner also matches a naive
        # `This is \S*TeX,` pattern, so `_last_engine_run` was treating it as
        # the final engine run and silently discarding the real last
        # pdflatex run's errors/warnings entirely.
        parsed = parse_log(TRAILING_BIBTEX_RUN_LOG)
        self.assertEqual(len(parsed.errors), 1)
        self.assertEqual(parsed.errors[0].message, "Undefined control sequence: \\multirow")
        self.assertEqual(len(parsed.warnings), 1)
        self.assertEqual(parsed.warnings[0].message, "There were undefined references.")

    def test_warning_resolved_by_a_later_rerun_is_not_reported(self):
        # latexmk reruns pdflatex after bibtex resolves citations; only the
        # last run's output should count, not the "Citation undefined" from
        # the very first pass.
        parsed = parse_log(MULTI_RUN_RESOLVED_CITATION_LOG)
        self.assertEqual(parsed.warnings, [])
        self.assertEqual(parsed.errors, [])
