"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-d30v9^pq_j)mwa)e38oqwuc$ep#^v^61-jvqf0($*-mhbx#_6h',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h for h in _allowed_hosts.split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'anymail',
    'ninja',
    'health',
    'accounts',
    'projects',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.CurrentUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Django only populates request.FILES for POST by design (a long-standing
    # historical quirk, see https://code.djangoproject.com/ticket/12635) — ninja's
    # own documented fix, needed for multipart PUT endpoints like
    # replace_file_binary_content (projects/files_api.py).
    'ninja.compatibility.files.fix_request_files_middleware',
]

if not DEBUG:
    # Serves collected static files straight from gunicorn in production
    # (see STATICFILES_STORAGE below). Skipped in dev — collectstatic never
    # runs there, so STATIC_ROOT doesn't exist and the middleware just warns.
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

# --- FreeLeaf auth (Plan.md §8/§9 Phase 1) ---
# ORCID / magic-link / anonymous sign-in; no passwords. See accounts app.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# 'localhost' and '127.0.0.1' are different origins (and different *sites*,
# since one's a domain and one's a bare IP) to a browser, even though they
# point at the same box — dev browsers commonly hit either. Cookies set by
# the api won't bridge the two regardless (recommend accessing the app via
# the same hostname consistently — see README), but at minimum both must be
# allowed here or CORS rejects the request outright before cookies matter.
_default_dev_origins = 'http://localhost:5173,http://127.0.0.1:5173'

_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', _default_dev_origins)
CORS_ALLOWED_ORIGINS = [o for o in _cors_origins.split(',') if o]
CORS_ALLOW_CREDENTIALS = True

_csrf_trusted = os.environ.get('CSRF_TRUSTED_ORIGINS', _default_dev_origins)
CSRF_TRUSTED_ORIGINS = [o for o in _csrf_trusted.split(',') if o]

# Only needed for a split-subdomain deployment (web and api on different
# hosts under one parent domain — see .env.prod.example topology B). The
# session cookie already works fine across subdomains with no extra config
# (subdomains are "same-site", so the browser resends it automatically) —
# but the CSRF cookie's value has to be *read* by the web app's own JS
# (to echo back as the X-CSRFToken header), and by default the cookie is
# host-only: scoped to the api's exact host, invisible to document.cookie
# on a *different* host even under the same parent domain. Setting this to
# the shared parent (e.g. ".example.com") makes the cookie visible to both.
# Leave unset for the same-origin topology (default) — host-only is correct
# there since web and api share one host.
CSRF_COOKIE_DOMAIN = os.environ.get('CSRF_COOKIE_DOMAIN') or None

# Real-time collaboration (PLAN.md §6/Phase 5). Shared with apps/collab —
# must be identical on both services (see docker-compose.yml). Signs the
# short-lived collab-token issued by GET .../collab-token so the Node
# service can verify a WS connection's project/file/role without its own
# session/DB access. COLLAB_WS_URL is what the browser is told to connect
# to; defaults to the dev collab service's own port.
COLLAB_SHARED_SECRET = os.environ.get('COLLAB_SHARED_SECRET', 'dev-insecure-collab-secret')
COLLAB_WS_URL = os.environ.get('COLLAB_WS_URL', 'ws://localhost:1234')
# Docker-network address api itself uses to call collab's internal HTTP
# endpoints (e.g. force-flushing a room before compiling) — distinct from
# COLLAB_WS_URL, which is the *browser*-facing address and is never reachable
# from inside this container.
COLLAB_INTERNAL_URL = os.environ.get('COLLAB_INTERNAL_URL', 'http://collab:1234')

# Mailpit in dev (see docker-compose.yml); Mailgun (via django-anymail) in
# production when MAILGUN_API_KEY is set (see docker-compose.prod.yml).
MAILGUN_API_KEY = os.environ.get('MAILGUN_API_KEY')
if MAILGUN_API_KEY:
    EMAIL_BACKEND = 'anymail.backends.mailgun.EmailBackend'
    ANYMAIL = {
        'MAILGUN_API_KEY': MAILGUN_API_KEY,
        'MAILGUN_SENDER_DOMAIN': os.environ.get('MAILGUN_DOMAIN', ''),
    }
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'mailpit')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '1025'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'false').lower() == 'true'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@freeleaf.local')

# Production hardening — SECURE_PROXY_SSL_HEADER is safe in dev too (no-op
# without a matching header from a trusted proxy). The cookie/HSTS settings
# are gated on DEBUG so local dev over plain http keeps working.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
X_FRAME_OPTIONS = 'DENY'
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'freeleaf'),
        'USER': os.environ.get('POSTGRES_USER', 'freeleaf'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'freeleaf'),
        'HOST': os.environ.get('POSTGRES_HOST', 'postgres'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Manifest storage requires collectstatic to have run (see Dockerfile.prod /
# docker-compose.prod.yml) — falls back to plain storage in dev, where we
# never run collectstatic and DEBUG-mode runserver serves static files itself.
STATICFILES_STORAGE = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
    if not DEBUG
    else 'django.contrib.staticfiles.storage.StaticFilesStorage'
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging — plain stdout so `docker compose logs api` (dev) or
# `docker compose -f docker-compose.prod.yml logs api` (prod) shows it; no
# separate log file/aggregator wired up. DJANGO_LOG_LEVEL controls verbosity
# without a redeploy needed beyond restarting the container with the env var
# set — DEBUG is very chatty (includes SQL), INFO is the practical default,
# WARNING quiets it down once something's confirmed working.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}
