# Generated by Django 5.1.15 on 2026-07-11 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_admin_user_last_login_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SsoProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('saml', 'SAML (Shibboleth)'), ('ldap', 'LDAP / Active Directory')], max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saml_idp_entity_id', models.CharField(blank=True, max_length=512)),
                ('saml_idp_sso_url', models.URLField(blank=True)),
                ('saml_idp_x509_cert', models.TextField(blank=True)),
                ('saml_email_attribute', models.CharField(blank=True, default='email', max_length=255)),
                ('saml_display_name_attribute', models.CharField(blank=True, default='displayName', max_length=255)),
                ('ldap_server_uri', models.CharField(blank=True, max_length=255)),
                ('ldap_bind_dn', models.CharField(blank=True, max_length=255)),
                ('ldap_bind_password_encrypted', models.TextField(blank=True)),
                ('ldap_user_search_base', models.CharField(blank=True, max_length=255)),
                ('ldap_user_search_filter', models.CharField(blank=True, default='(uid=%(user)s)', max_length=255)),
                ('ldap_email_attribute', models.CharField(blank=True, default='mail', max_length=255)),
                ('ldap_display_name_attribute', models.CharField(blank=True, default='displayName', max_length=255)),
                ('ldap_use_starttls', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='sso_external_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kind',
            field=models.CharField(choices=[('orcid', 'ORCID'), ('email', 'Email'), ('anonymous', 'Anonymous'), ('sso', 'Institutional SSO')], max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='sso_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.ssoprovider'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'sso')), fields=('sso_provider', 'sso_external_id'), name='unique_external_id_per_sso_provider'),
        ),
    ]
