# Generated by Django 5.1.15 on 2026-07-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ssoprovider_user_sso_external_id_alter_user_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcid_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
