# Generated by Django 5.1.15 on 2026-07-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='FreeLeaf', max_length=100),
        ),
    ]
