# Generated by Django 5.1.15 on 2026-07-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sitesettings_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='template_contribution_mode',
            field=models.CharField(choices=[('admin_only', 'Admins only'), ('review_required', 'Anyone, pending admin review'), ('open', 'Anyone, published immediately')], default='admin_only', max_length=20),
        ),
    ]
