/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_views_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Csrf */
        get: operations["accounts_api_get_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["accounts_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/site-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Site Info */
        get: operations["accounts_api_site_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["accounts_api_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/anonymous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anonymous Login */
        post: operations["accounts_api_anonymous_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/magic-link/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Magic Link Request */
        post: operations["accounts_api_magic_link_request"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/magic-link/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Magic Link Verify */
        post: operations["accounts_api_magic_link_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/orcid/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orcid Login */
        get: operations["accounts_api_orcid_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/orcid/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orcid Callback */
        get: operations["accounts_api_orcid_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["projects_api_list_projects"];
        put?: never;
        /** Create Project */
        post: operations["projects_api_create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Project Zip
         * @description Create a new project from an uploaded .zip (Plan.md §9 Phase 7).
         *     Unsafe or junk entries (path traversal, absolute paths, OS metadata
         *     like __MACOSX/.DS_Store, dotfiles) are silently skipped rather than
         *     failing the whole import — the same "validate every entry independently,
         *     never trust the archive" discipline as the compile sandbox's tar
         *     extraction (apps/compile/sandbox.py's _safe_extract), applied here to
         *     Python's zipfile instead of tarfile.
         */
        post: operations["projects_api_import_project_zip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Project Zip
         * @description Download the project's current files as a .zip — the counterpart to
         *     /projects/import. Any member can export (same access level as reading
         *     file content elsewhere); no role restriction. Folders aren't preserved
         *     as empty entries, mirroring import's own file-only handling.
         */
        get: operations["projects_api_export_project_zip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["projects_api_get_project"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["projects_api_delete_project"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["projects_api_update_project"];
        trace?: never;
    };
    "/api/projects/{project_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Members
         * @description Who currently has access and at what level — shown in the Share
         *     popover (Plan.md §9 Phase 7). Owner-only, same visibility as share-links:
         *     the Share button that surfaces this is itself only rendered for owners.
         */
        get: operations["projects_api_list_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/members/{member_user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["projects_api_remove_member"];
        options?: never;
        head?: never;
        /** Update Member Role */
        patch: operations["projects_api_update_member_role"];
        trace?: never;
    };
    "/api/projects/{project_id}/share-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Share Links */
        get: operations["projects_api_list_share_links"];
        put?: never;
        /** Create Share Link */
        post: operations["projects_api_create_share_link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/share-links/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Share Link */
        delete: operations["projects_api_revoke_share_link"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/share-links/{token}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Via Share Link */
        post: operations["projects_api_join_via_share_link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["projects_files_api_list_files"];
        put?: never;
        /** Create File */
        post: operations["projects_files_api_create_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Folder */
        post: operations["projects_files_api_create_folder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload File */
        post: operations["projects_files_api_upload_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/files/{file_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File Content */
        get: operations["projects_files_api_get_file_content"];
        /** Update File Content */
        put: operations["projects_files_api_update_file_content"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete File */
        delete: operations["projects_files_api_delete_file"];
        options?: never;
        head?: never;
        /** Rename File */
        patch: operations["projects_files_api_rename_file"];
        trace?: never;
    };
    "/api/projects/{project_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["projects_compile_api_get_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["projects_compile_api_update_settings"];
        trace?: never;
    };
    "/api/projects/{project_id}/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Compile */
        post: operations["projects_compile_api_trigger_compile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/compile-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Compile Runs */
        get: operations["projects_compile_api_list_compile_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/compile-runs/{run_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Compile Pdf */
        get: operations["projects_compile_api_get_compile_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/compile-runs/{run_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Compile Log */
        get: operations["projects_compile_api_get_compile_log"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/compile-runs/{run_id}/synctex/forward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Synctex Forward
         * @description Source position -> PDF position, for jumping the PDF pane to match
         *     the editor cursor ("both ways" click-to-source, Plan.md §9 Phase 7).
         */
        get: operations["projects_compile_api_synctex_forward"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/compile-runs/{run_id}/synctex/backward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Synctex Backward
         * @description PDF position -> source position, for jumping the editor to match a
         *     click in the PDF pane.
         */
        get: operations["projects_compile_api_synctex_backward"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/files/{file_id}/collab-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Collab Token */
        get: operations["projects_collab_api_get_collab_token"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/collab/files/{file_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Internal Get Content */
        get: operations["projects_collab_api_internal_get_content"];
        /** Internal Put Content */
        put: operations["projects_collab_api_internal_put_content"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/bibliography": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bibliography File */
        get: operations["projects_bibliography_api_get_bibliography_file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["accounts_admin_api_list_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["accounts_admin_api_delete_user"];
        options?: never;
        head?: never;
        /** Update User Admin */
        patch: operations["accounts_admin_api_update_user_admin"];
        trace?: never;
    };
    "/api/admin/site-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Site Settings */
        get: operations["accounts_admin_api_get_site_settings"];
        /** Update Site Settings */
        put: operations["accounts_admin_api_update_site_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["projects_versions_api_list_snapshots"];
        put?: never;
        /** Create Snapshot */
        post: operations["projects_versions_api_create_snapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/snapshots/{snapshot_id}/file-content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot File Content */
        get: operations["projects_versions_api_get_snapshot_file_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/snapshots/{snapshot_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Snapshot
         * @description Makes the project's files match the target snapshot exactly:
         *     existing files are overwritten, files missing since the snapshot are
         *     recreated, and files that didn't exist at snapshot time are deleted.
         *     A safety snapshot of the *current* state is taken first — nothing is
         *     ever truly lost, since restoring is itself always just a restore away.
         */
        post: operations["projects_versions_api_restore_snapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/files/{file_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Comments */
        get: operations["projects_comments_api_list_comments"];
        put?: never;
        /** Create Comment */
        post: operations["projects_comments_api_create_comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/comments/{comment_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Resolve Comment */
        patch: operations["projects_comments_api_resolve_comment"];
        trace?: never;
    };
    "/api/projects/{project_id}/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Comment */
        delete: operations["projects_comments_api_delete_comment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sso/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Public Providers */
        get: operations["accounts_sso_api_list_public_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/ldap/{slug}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ldap Login */
        post: operations["accounts_sso_api_ldap_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/saml/{slug}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saml Metadata */
        get: operations["accounts_sso_api_saml_metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/saml/{slug}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saml Login */
        get: operations["accounts_sso_api_saml_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/saml/{slug}/acs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Saml Acs */
        post: operations["accounts_sso_api_saml_acs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sso-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["accounts_sso_admin_api_list_providers"];
        put?: never;
        /** Create Provider */
        post: operations["accounts_sso_admin_api_create_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sso-providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Provider */
        delete: operations["accounts_sso_admin_api_delete_provider"];
        options?: never;
        head?: never;
        /** Update Provider */
        patch: operations["accounts_sso_admin_api_update_provider"];
        trace?: never;
    };
    "/api/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Setup Status */
        get: operations["accounts_setup_api_setup_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/orcid-enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Setup Set Orcid Enabled */
        put: operations["accounts_setup_api_setup_set_orcid_enabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/request-admin-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Admin Link */
        post: operations["accounts_setup_api_request_admin_link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/verify-admin-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Admin Link */
        post: operations["accounts_setup_api_verify_admin_link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Orcid Id */
            orcid_id?: string | null;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
        /** SiteInfoOut */
        SiteInfoOut: {
            /** Site Name */
            site_name: string;
        };
        /** AnonymousLoginIn */
        AnonymousLoginIn: {
            /** Display Name */
            display_name?: string | null;
        };
        /** MagicLinkRequestIn */
        MagicLinkRequestIn: {
            /** Email */
            email: string;
            /** Next */
            next?: string | null;
            /** Share Link Token */
            share_link_token: string;
        };
        /** MagicLinkVerifyIn */
        MagicLinkVerifyIn: {
            /** Token */
            token: string;
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Last Edited By Name */
            last_edited_by_name?: string | null;
        };
        /** ProjectCreateIn */
        ProjectCreateIn: {
            /** Name */
            name: string;
        };
        /** ProjectUpdateIn */
        ProjectUpdateIn: {
            /** Name */
            name: string;
        };
        /** MemberOut */
        MemberOut: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Display Name */
            display_name: string;
            /** Kind */
            kind: string;
            /** Role */
            role: string;
            /** Is You */
            is_you: boolean;
        };
        /** MemberUpdateIn */
        MemberUpdateIn: {
            /** Role */
            role: string;
        };
        /** ShareLinkOut */
        ShareLinkOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Expires At */
            expires_at?: string | null;
            /** Created At */
            created_at: string;
            /** Token */
            token?: string | null;
        };
        /** ShareLinkCreateIn */
        ShareLinkCreateIn: {
            /**
             * Role
             * @default editor
             */
            role: string;
            /** Expires In Hours */
            expires_in_hours?: number | null;
        };
        /** ShareLinkJoinIn */
        ShareLinkJoinIn: {
            /** Display Name */
            display_name?: string | null;
        };
        /** ProjectFileOut */
        ProjectFileOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Path */
            path: string;
            /** Type */
            type: string;
            /** Size */
            size: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** FileCreateIn */
        FileCreateIn: {
            /** Path */
            path: string;
            /**
             * Content
             * @default
             */
            content: string;
        };
        /** FolderCreateIn */
        FolderCreateIn: {
            /** Path */
            path: string;
        };
        /** FileContentIn */
        FileContentIn: {
            /** Content */
            content: string;
        };
        /** FileRenameIn */
        FileRenameIn: {
            /** Path */
            path: string;
        };
        /** ProjectSettingsOut */
        ProjectSettingsOut: {
            /** Main Doc Path */
            main_doc_path: string;
            /** Central Bib Path */
            central_bib_path?: string | null;
            /** Compiler */
            compiler: string;
            /** Bib Engine */
            bib_engine: string;
            /** Cite Autocomplete Enabled */
            cite_autocomplete_enabled: boolean;
        };
        /** ProjectSettingsIn */
        ProjectSettingsIn: {
            /** Main Doc Path */
            main_doc_path?: string | null;
            /** Central Bib Path */
            central_bib_path?: string | null;
            /** Compiler */
            compiler?: string | null;
            /** Bib Engine */
            bib_engine?: string | null;
            /** Cite Autocomplete Enabled */
            cite_autocomplete_enabled?: boolean | null;
        };
        /** CompileRunOut */
        CompileRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Compiler */
            compiler: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Exit Code */
            exit_code?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Has Pdf */
            has_pdf: boolean;
            /** Errors */
            errors: components["schemas"]["DiagnosticOut"][];
            /** Warnings */
            warnings: components["schemas"]["DiagnosticOut"][];
        };
        /** DiagnosticOut */
        DiagnosticOut: {
            /** Message */
            message: string;
            /** File */
            file?: string | null;
            /** Line */
            line?: number | null;
        };
        /** SyncTexForwardOut */
        SyncTexForwardOut: {
            /** Page */
            page: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** H */
            h: number;
            /** V */
            v: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** SyncTexBackwardOut */
        SyncTexBackwardOut: {
            /** File */
            file: string;
            /** Line */
            line: number;
            /** Column */
            column: number;
        };
        /** CollabTokenOut */
        CollabTokenOut: {
            /** Token */
            token: string;
            /** Ws Url */
            ws_url: string;
        };
        /** InternalContentIn */
        InternalContentIn: {
            /** Content */
            content: string;
            /** Editor User Id */
            editor_user_id?: string | null;
        };
        /** BibliographyFileOut */
        BibliographyFileOut: {
            /**
             * File Id
             * Format: uuid
             */
            file_id: string;
            /** Path */
            path: string;
        };
        /** AdminUserOut */
        AdminUserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Orcid Id */
            orcid_id?: string | null;
            /** Is Admin */
            is_admin: boolean;
            /** Created At */
            created_at: string;
            /** Last Login At */
            last_login_at?: string | null;
            /** Project Count */
            project_count: number;
        };
        /** UpdateUserAdminIn */
        UpdateUserAdminIn: {
            /** Is Admin */
            is_admin: boolean;
        };
        /** SiteSettingsOut */
        SiteSettingsOut: {
            /** Orcid Enabled */
            orcid_enabled: boolean;
            /** Orcid Configured */
            orcid_configured: boolean;
            /** Site Name */
            site_name: string;
        };
        /** SiteSettingsIn */
        SiteSettingsIn: {
            /** Orcid Enabled */
            orcid_enabled: boolean;
            /** Site Name */
            site_name: string;
        };
        /** SnapshotOut */
        SnapshotOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Created At */
            created_at: string;
            /** Created By Name */
            created_by_name?: string | null;
        };
        /** SnapshotCreateIn */
        SnapshotCreateIn: {
            /**
             * Kind
             * @default manual
             */
            kind: string;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** SnapshotFileOut */
        SnapshotFileOut: {
            /** Content */
            content: string;
        };
        /** RestoreOut */
        RestoreOut: {
            restored_to: components["schemas"]["SnapshotOut"];
            safety_snapshot?: components["schemas"]["SnapshotOut"] | null;
        };
        /** CommentOut */
        CommentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Anchor Line */
            anchor_line: number;
            /** Anchor From */
            anchor_from?: number | null;
            /** Anchor To */
            anchor_to?: number | null;
            /** Anchor Text */
            anchor_text?: string | null;
            /** Body */
            body: string;
            /** Created At */
            created_at: string;
            /** Created By Name */
            created_by_name?: string | null;
            /**
             * Is You
             * @default false
             */
            is_you: boolean;
            /**
             * Can Delete
             * @default false
             */
            can_delete: boolean;
            /** Resolved */
            resolved: boolean;
            /** Resolved By Name */
            resolved_by_name?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /** Replies */
            replies: components["schemas"]["ReplyOut"][];
        };
        /** ReplyOut */
        ReplyOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Body */
            body: string;
            /** Created At */
            created_at: string;
            /** Created By Name */
            created_by_name?: string | null;
            /**
             * Is You
             * @default false
             */
            is_you: boolean;
        };
        /** CommentCreateIn */
        CommentCreateIn: {
            /**
             * Anchor Line
             * @default 1
             */
            anchor_line: number;
            /** Anchor From */
            anchor_from?: number | null;
            /** Anchor To */
            anchor_to?: number | null;
            /** Anchor Text */
            anchor_text?: string | null;
            /** Body */
            body: string;
            /** Parent Id */
            parent_id?: string | null;
        };
        /** ResolveIn */
        ResolveIn: {
            /**
             * Resolved
             * @default true
             */
            resolved: boolean;
        };
        /** SsoProviderPublicOut */
        SsoProviderPublicOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
        };
        /** LdapLoginIn */
        LdapLoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** SsoProviderAdminOut */
        SsoProviderAdminOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Kind */
            kind: string;
            /** Enabled */
            enabled: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Saml Idp Entity Id */
            saml_idp_entity_id: string;
            /** Saml Idp Sso Url */
            saml_idp_sso_url: string;
            /** Saml Idp X509 Cert */
            saml_idp_x509_cert: string;
            /** Saml Email Attribute */
            saml_email_attribute: string;
            /** Saml Display Name Attribute */
            saml_display_name_attribute: string;
            /** Ldap Server Uri */
            ldap_server_uri: string;
            /** Ldap Bind Dn */
            ldap_bind_dn: string;
            /** Ldap Has Bind Password */
            ldap_has_bind_password: boolean;
            /** Ldap User Search Base */
            ldap_user_search_base: string;
            /** Ldap User Search Filter */
            ldap_user_search_filter: string;
            /** Ldap Email Attribute */
            ldap_email_attribute: string;
            /** Ldap Display Name Attribute */
            ldap_display_name_attribute: string;
            /** Ldap Use Starttls */
            ldap_use_starttls: boolean;
        };
        /** SsoProviderCreateIn */
        SsoProviderCreateIn: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Kind */
            kind: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Saml Idp Entity Id
             * @default
             */
            saml_idp_entity_id: string;
            /**
             * Saml Idp Sso Url
             * @default
             */
            saml_idp_sso_url: string;
            /**
             * Saml Idp X509 Cert
             * @default
             */
            saml_idp_x509_cert: string;
            /**
             * Saml Email Attribute
             * @default email
             */
            saml_email_attribute: string;
            /**
             * Saml Display Name Attribute
             * @default displayName
             */
            saml_display_name_attribute: string;
            /**
             * Ldap Server Uri
             * @default
             */
            ldap_server_uri: string;
            /**
             * Ldap Bind Dn
             * @default
             */
            ldap_bind_dn: string;
            /**
             * Ldap Bind Password
             * @default
             */
            ldap_bind_password: string;
            /**
             * Ldap User Search Base
             * @default
             */
            ldap_user_search_base: string;
            /**
             * Ldap User Search Filter
             * @default (uid=%(user)s)
             */
            ldap_user_search_filter: string;
            /**
             * Ldap Email Attribute
             * @default mail
             */
            ldap_email_attribute: string;
            /**
             * Ldap Display Name Attribute
             * @default displayName
             */
            ldap_display_name_attribute: string;
            /**
             * Ldap Use Starttls
             * @default false
             */
            ldap_use_starttls: boolean;
        };
        /** SsoProviderUpdateIn */
        SsoProviderUpdateIn: {
            /** Name */
            name?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Saml Idp Entity Id */
            saml_idp_entity_id?: string | null;
            /** Saml Idp Sso Url */
            saml_idp_sso_url?: string | null;
            /** Saml Idp X509 Cert */
            saml_idp_x509_cert?: string | null;
            /** Saml Email Attribute */
            saml_email_attribute?: string | null;
            /** Saml Display Name Attribute */
            saml_display_name_attribute?: string | null;
            /** Ldap Server Uri */
            ldap_server_uri?: string | null;
            /** Ldap Bind Dn */
            ldap_bind_dn?: string | null;
            /** Ldap Bind Password */
            ldap_bind_password?: string | null;
            /** Ldap User Search Base */
            ldap_user_search_base?: string | null;
            /** Ldap User Search Filter */
            ldap_user_search_filter?: string | null;
            /** Ldap Email Attribute */
            ldap_email_attribute?: string | null;
            /** Ldap Display Name Attribute */
            ldap_display_name_attribute?: string | null;
            /** Ldap Use Starttls */
            ldap_use_starttls?: boolean | null;
        };
        /** SetupStatusOut */
        SetupStatusOut: {
            /** Needs Setup */
            needs_setup: boolean;
            /** Orcid Available */
            orcid_available: boolean;
            /** Orcid Configured */
            orcid_configured: boolean;
            /** Orcid Enabled */
            orcid_enabled: boolean;
        };
        /** SetupOrcidIn */
        SetupOrcidIn: {
            /** Orcid Enabled */
            orcid_enabled: boolean;
        };
        /** RequestAdminLinkIn */
        RequestAdminLinkIn: {
            /** Email */
            email: string;
        };
        /** VerifyAdminLinkIn */
        VerifyAdminLinkIn: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_views_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_api_get_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"] | null;
                };
            };
        };
    };
    accounts_api_site_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteInfoOut"];
                };
            };
        };
    };
    accounts_api_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_api_anonymous_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnonymousLoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    accounts_api_magic_link_request: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequestIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_api_magic_link_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkVerifyIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    accounts_api_orcid_login: {
        parameters: {
            query?: {
                next?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_api_orcid_callback: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_api_list_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    projects_api_create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    projects_api_import_project_zip: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    projects_api_export_project_zip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_api_get_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    projects_api_delete_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_api_update_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    projects_api_list_members: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"][];
                };
            };
        };
    };
    projects_api_remove_member: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                member_user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_api_update_member_role: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                member_user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
        };
    };
    projects_api_list_share_links: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareLinkOut"][];
                };
            };
        };
    };
    projects_api_create_share_link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareLinkCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareLinkOut"];
                };
            };
        };
    };
    projects_api_revoke_share_link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_api_join_via_share_link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareLinkJoinIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
        };
    };
    projects_files_api_list_files: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFileOut"][];
                };
            };
        };
    };
    projects_files_api_create_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFileOut"];
                };
            };
        };
    };
    projects_files_api_create_folder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFileOut"];
                };
            };
        };
    };
    projects_files_api_upload_file: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFileOut"];
                };
            };
        };
    };
    projects_files_api_get_file_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_files_api_update_file_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileContentIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFileOut"];
                };
            };
        };
    };
    projects_files_api_delete_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_files_api_rename_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileRenameIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFileOut"];
                };
            };
        };
    };
    projects_compile_api_get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSettingsOut"];
                };
            };
        };
    };
    projects_compile_api_update_settings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectSettingsIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSettingsOut"];
                };
            };
        };
    };
    projects_compile_api_trigger_compile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileRunOut"];
                };
            };
        };
    };
    projects_compile_api_list_compile_runs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileRunOut"][];
                };
            };
        };
    };
    projects_compile_api_get_compile_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_compile_api_get_compile_log: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_compile_api_synctex_forward: {
        parameters: {
            query: {
                file: string;
                line: number;
            };
            header?: never;
            path: {
                project_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncTexForwardOut"];
                };
            };
        };
    };
    projects_compile_api_synctex_backward: {
        parameters: {
            query: {
                page: number;
                x: number;
                y: number;
            };
            header?: never;
            path: {
                project_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncTexBackwardOut"];
                };
            };
        };
    };
    projects_collab_api_get_collab_token: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollabTokenOut"];
                };
            };
        };
    };
    projects_collab_api_internal_get_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_collab_api_internal_put_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InternalContentIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_bibliography_api_get_bibliography_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BibliographyFileOut"];
                };
            };
        };
    };
    accounts_admin_api_list_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"][];
                };
            };
        };
    };
    accounts_admin_api_delete_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_admin_api_update_user_admin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserAdminIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"];
                };
            };
        };
    };
    accounts_admin_api_get_site_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteSettingsOut"];
                };
            };
        };
    };
    accounts_admin_api_update_site_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteSettingsIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteSettingsOut"];
                };
            };
        };
    };
    projects_versions_api_list_snapshots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"][];
                };
            };
        };
    };
    projects_versions_api_create_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"];
                };
            };
        };
    };
    projects_versions_api_get_snapshot_file_content: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                project_id: string;
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotFileOut"];
                };
            };
        };
    };
    projects_versions_api_restore_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreOut"];
                };
            };
        };
    };
    projects_comments_api_list_comments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentOut"][];
                };
            };
        };
    };
    projects_comments_api_create_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentOut"];
                };
            };
        };
    };
    projects_comments_api_resolve_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                comment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentOut"];
                };
            };
        };
    };
    projects_comments_api_delete_comment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                comment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_sso_api_list_public_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoProviderPublicOut"][];
                };
            };
        };
    };
    accounts_sso_api_ldap_login: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LdapLoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    accounts_sso_api_saml_metadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_sso_api_saml_login: {
        parameters: {
            query?: {
                next?: string | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_sso_api_saml_acs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_sso_admin_api_list_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoProviderAdminOut"][];
                };
            };
        };
    };
    accounts_sso_admin_api_create_provider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SsoProviderCreateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoProviderAdminOut"];
                };
            };
        };
    };
    accounts_sso_admin_api_delete_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_sso_admin_api_update_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SsoProviderUpdateIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SsoProviderAdminOut"];
                };
            };
        };
    };
    accounts_setup_api_setup_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
        };
    };
    accounts_setup_api_setup_set_orcid_enabled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupOrcidIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
        };
    };
    accounts_setup_api_request_admin_link: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestAdminLinkIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_setup_api_verify_admin_link: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyAdminLinkIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
}
