# Generated by Django 5.1.15 on 2026-07-10 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=512)),
                ('type', models.CharField(choices=[('tex', 'TeX'), ('bib', 'BibTeX'), ('image', 'Image'), ('other', 'Other'), ('folder', 'Folder')], max_length=16)),
                ('storage_key', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'path'), name='unique_path_per_project')],
            },
        ),
    ]
