# Generated by Django 5.1.15 on 2026-07-10 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompileRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compiler', models.CharField(choices=[('pdflatex', 'pdfLaTeX'), ('xelatex', 'XeLaTeX')], max_length=16)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_key', models.CharField(blank=True, max_length=255, null=True)),
                ('log_key', models.CharField(blank=True, max_length=255, null=True)),
                ('synctex_key', models.CharField(blank=True, max_length=255, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compile_runs', to='projects.project')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_doc_path', models.CharField(default='main.tex', max_length=512)),
                ('central_bib_path', models.CharField(blank=True, max_length=512, null=True)),
                ('compiler', models.CharField(choices=[('pdflatex', 'pdfLaTeX'), ('xelatex', 'XeLaTeX')], default='pdflatex', max_length=16)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='projects.project')),
            ],
        ),
    ]
