# Generated by Django 5.1.15 on 2026-07-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_compilerun_projectsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilerun',
            name='errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='compilerun',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
