# Generated by Django 5.1.15 on 2026-07-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_compilerun_errors_compilerun_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='bib_engine',
            field=models.CharField(choices=[('bibtex', 'BibTeX'), ('biber', 'Biber')], default='bibtex', max_length=16),
        ),
    ]
