# Generated by Django 5.1.15 on 2026-07-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectsettings_bib_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='cite_autocomplete_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
