# Generated by Django 5.1.15 on 2026-07-11 04:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_admin_user_last_login_at'),
        ('projects', '0006_projectsettings_cite_autocomplete_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=16)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('archive_key', models.CharField(max_length=255)),
                ('content_hash', models.CharField(default='', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
