# Generated by Django 5.1.15 on 2026-07-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anchor_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='anchor_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='anchor_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
