# Generated by Django 5.1.15 on 2026-07-12 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_sitesettings_site_name'),
        ('projects', '0009_comment_anchor_from_comment_anchor_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.user'),
        ),
    ]
