# Generated by Django 5.1.15 on 2026-07-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_last_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer')], max_length=16),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer')], default='editor', max_length=16),
        ),
    ]
