# Generated by Django 5.1.15 on 2026-07-14 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sitesettings_template_contribution_mode'),
        ('projects', '0011_alter_membership_role_alter_sharelink_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('zip_storage_key', models.CharField(max_length=255)),
                ('thumbnail_storage_key', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
    ]
