# Generated by Django 5.1.15 on 2026-07-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='thumbnail_content_type',
        ),
        migrations.RemoveField(
            model_name='template',
            name='thumbnail_storage_key',
        ),
    ]
