# Generated by Django 5.1.15 on 2026-07-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_template_thumbnail_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail_storage_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
