# Generated by Django 5.1.15 on 2026-07-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_thumbnail_storage_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilerun',
            name='job_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
