# Generated by Django 5.1.15 on 2026-10-08 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sitesettings_template_contribution_mode'),
        ('projects', '0015_compilerun_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_collections', to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='projects.projectcollection'),
        ),
        migrations.AddConstraint(
            model_name='projectcollection',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_collection_name_per_owner'),
        ),
    ]
